name: clock-in

on:
  schedule:
    - cron: '55 23 * * 6'
    - cron: '55 23 * * 0-2'
    - cron: '55 1 * * 4-5'
    - cron: '55 3 * * 6'


  workflow_dispatch:

jobs:
  Clock_in:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - run: pip3 install -r requirements.txt
      - run: sudo apt-get install libzbar-dev
      - run: pip install pyzbar
      - run: python XueQG.py
